package report

import (
	"fmt"
	"strings"
)

// renderMarkdown generates a full markdown report.
func renderMarkdown(data *ReportData) string {
	tech := BuildTechnicalReport(data)
	exec := tech.Executive

	var b strings.Builder

	// Title.
	b.WriteString("# 3A Assessment Report\n\n")

	// Executive Summary.
	b.WriteString("## Executive Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Provider:** %s\n", exec.Provider))
	b.WriteString(fmt.Sprintf("- **Profile:** %s\n", exec.Profile))
	b.WriteString(fmt.Sprintf("- **Risk Level:** %s\n", exec.RiskLevel()))
	b.WriteString(fmt.Sprintf("- **Total Resources:** %d\n", exec.TotalResources))
	b.WriteString(fmt.Sprintf("- **Total Findings:** %d\n", exec.TotalFindings))
	b.WriteString(fmt.Sprintf("- **Estimated Monthly Cost:** $%.2f\n", exec.MonthlyCost))
	b.WriteString("\n")

	b.WriteString("### Finding Summary\n\n")
	b.WriteString("| Severity | Count |\n")
	b.WriteString("|----------|-------|\n")
	b.WriteString(fmt.Sprintf("| Critical | %d |\n", exec.CriticalCount))
	b.WriteString(fmt.Sprintf("| High     | %d |\n", exec.HighCount))
	b.WriteString(fmt.Sprintf("| Medium   | %d |\n", exec.MediumCount))
	b.WriteString(fmt.Sprintf("| Low      | %d |\n", exec.LowCount))
	b.WriteString("\n")

	if len(exec.TopRisks) > 0 {
		b.WriteString("### Top Risks\n\n")
		for i, risk := range exec.TopRisks {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, risk))
		}
		b.WriteString("\n")
	}

	// Resource Inventory.
	b.WriteString("## Resource Inventory\n\n")
	b.WriteString("### By Type\n\n")
	b.WriteString("| Resource Type | Count |\n")
	b.WriteString("|---------------|-------|\n")
	for rType, count := range tech.ResourcesByType {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", rType, count))
	}
	b.WriteString("\n")

	b.WriteString("### By Region\n\n")
	b.WriteString("| Region | Count |\n")
	b.WriteString("|--------|-------|\n")
	for region, count := range tech.ResourcesByRegion {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", region, count))
	}
	b.WriteString("\n")

	// Findings.
	b.WriteString("## Security Findings\n\n")
	for category, findings := range tech.FindingsByCategory {
		b.WriteString(fmt.Sprintf("### %s\n\n", category))
		for _, f := range findings {
			b.WriteString(fmt.Sprintf("- **[%s]** %s\n", strings.ToUpper(f.Severity), f.Description))
			b.WriteString(fmt.Sprintf("  - Recommendation: %s\n", f.Recommendation))
			b.WriteString(fmt.Sprintf("  - Control: %s\n", f.ControlID))
		}
		b.WriteString("\n")
	}

	// Cost Analysis.
	b.WriteString("## Cost Analysis\n\n")
	b.WriteString("### By Category\n\n")
	b.WriteString("| Category | Monthly Cost |\n")
	b.WriteString("|----------|-------------|\n")
	for cat, cost := range tech.CostBreakdown {
		b.WriteString(fmt.Sprintf("| %s | $%.2f |\n", cat, cost))
	}
	b.WriteString("\n")

	// Architecture.
	b.WriteString("## Architecture\n\n")
	b.WriteString(fmt.Sprintf("- **Relationships discovered:** %d\n", tech.Relationships))
	b.WriteString("\n")

	// Footer.
	b.WriteString("---\n")
	b.WriteString("*Generated by 3A (Agnostic Account Assessment)*\n")

	return b.String()
}
